/**
 * Deploy seed-sync (#60): the guard against code and D1 drifting apart.
 *
 * Adding a Blank in `src/libs/blank.ts` must never leave it invisible to the
 * database. This builds an idempotent statement that inserts a zero-stock row
 * for every code-defined Blank and — via `ON CONFLICT DO NOTHING` — leaves any
 * Blank that already has a row completely untouched, `on_hand` and all. Run on
 * every deploy against remote D1 (`npm run db:seed-sync:remote`); a Blank with
 * no row lands at 0, a Blank with real stock keeps it.
 *
 * Plain SQL, not a Drizzle write, on purpose: the seed-sync runs at deploy time
 * through `wrangler d1 execute --file`, outside any Worker request, so it has no
 * D1 binding to hand a Drizzle client. Keeping it as one generated statement
 * means the exact text that ships is the exact text a test can apply to a real
 * migrated D1 (see `stock.test.ts`).
 */
export const buildSeedSyncSql = (blankIds: readonly string[]): string => {
  if (blankIds.length === 0) {
    return "-- No code-defined Blanks; nothing to seed-sync.\n";
  }
  const values = blankIds
    .map((id) => `  ('${escapeSqlLiteral(id)}', 0)`)
    .join(",\n");
  return [
    "-- Generated by `npm run db:seed-sync` from src/libs/blank.ts.",
    "-- Idempotent: inserts a zero-stock row for any code-defined Blank missing",
    "-- from D1, and leaves existing rows (on_hand included) untouched.",
    "INSERT INTO stock (blank_id, on_hand) VALUES",
    `${values}`,
    "ON CONFLICT (blank_id) DO NOTHING;",
    "",
  ].join("\n");
};

/** Blank ids are code-defined slugs, but escape single quotes defensively so a
 * future id can never break the generated statement. */
const escapeSqlLiteral = (value: string): string => value.replace(/'/g, "''");
